yolo-weights=WEIGHTS #'yolov8s-seg.pt'
reid-weights=WEIGHTS #'osnet_x0_25_msmt17.pt')
tracking-method=strongsort
tracking-config=None
source='2'  
imgsz=[640]
conf-thres=0.5
iou-thres', type=float, default=0.5, help='NMS IoU threshold')
max-det', type=int, default=1000, help='maximum detections per image')
device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
show-vid', action='store_true', help='display tracking video results')
save-txt', action='store_true', help='save results to *.txt')
save-conf', action='store_true', help='save confidences in --save-txt labels')
save-crop', action='store_true', help='save cropped prediction boxes')
save-trajectories', action='store_true', help='save trajectories for each track')
save-vid', action='store_true', help='save video tracking results')
nosave', action='store_true', help='do not save images/videos')
# class 0 is person, 1 is bycicle, 2 is car... 79 is oven
classes', nargs='+', type=int, default=0, help='filter by class: --classes 0, or --classes 0 2 3')
agnostic-nms', action='store_true', help='class-agnostic NMS')
augment', action='store_true', help='augmented inference')
visualize', action='store_true', help='visualize features')
update', action='store_true', help='update all models')
project', default=ROOT / 'runs' / 'track', help='save results to project/name')
name', default='exp', help='save results to project/name')
exist-ok', action='store_true', help='existing project/name ok, do not increment')
line-thickness', default=2, type=int, help='bounding box thickness (pixels)')
hide-labels', default=False, action='store_true', help='hide labels')
hide-conf', default=False, action='store_true', help='hide confidences')
hide-class', default=False, action='store_true', help='hide IDs')
half', action='store_true', help='use FP16 half-precision inference')
dnn', action='store_true', help='use OpenCV DNN for ONNX inference')
vid-stride', type=int, default=1, help='video frame-rate stride')
retina-masks', action='store_true', help='whether to plot masks in native resolution')